[general]
name = "Sensus"

# [sensors]
# probe-present = true # not used right now

[plugged]
onboard-sample-interval = "10s"
probe-sample-interval = "10s"

[battery]
onboard-sample-interval = "30s"
probe-sample-interval = "30s"

# A look-up table can be used to calibrate the probe. Maximum 10 points.
[probe_calibration]
1600000 = "0%"
100000 = "100%"
